#!/usr/bin/env bash
# Compares the built Rust crate's output against tests/golden/checksums.sha256
# -- SHA-256 hashes of frozen "golden" output -- instead of rebuilding the C
# toolchain from source and comparing against that on every run.
#
# The golden checksums were captured from the Rust build at a point where
# rust/scripts/compare-with-c.sh had just confirmed it byte-identical to C
# on every payload (see rust/README.md for when and how); they are C's
# approval, frozen. This script re-validates the crate against that frozen
# snapshot without needing c/ present, built, or even checked out --
# c/ can now fall behind, be archived, or be removed without losing the
# regression safety net compare-with-c.sh used to provide.
#
# Hashes, not the dump JSON / build output files themselves: see the header
# of generate-golden.sh for why (repo size). tests/golden/dll-test.otf is
# the one exception, kept as a real file -- also explained there.
#
# If a change *legitimately* alters output (a real bug fix, a new feature),
# regenerate the checksums this script checks against with
# rust/scripts/generate-golden.sh and commit the result alongside the
# change that motivated it -- don't hand-edit tests/golden/checksums.sha256.
#
# Must run AFTER the Rust crate has been built (cargo build --release).
#
# Invoke as: ./rust/scripts/compare-with-golden.sh
set -euo pipefail
cd "$(dirname "$0")/../.."
. rust/scripts/sha256-of.sh

RUST_BIN=rust/target/release
if [ ! -x "${RUST_BIN}/otfccdump" ] || [ ! -x "${RUST_BIN}/otfccbuild" ]; then
	echo "ERROR: ${RUST_BIN}/{otfccdump,otfccbuild} not found; build the Rust crate first." >&2
	exit 1
fi

GOLDEN=tests/golden
CHECKSUMS="${GOLDEN}/checksums.sha256"
BUILD=build/compare-with-golden
mkdir -p "${BUILD}"

fail=0

golden_hash_of() {
	# golden_hash_of <label> -- prints the recorded hash, or nothing (and a
	# script-fatal message) if the label isn't in the manifest at all,
	# which means generate-golden.sh needs to be run, not that the payload
	# legitimately has no expectation.
	local label="$1" hash
	hash=$(awk -v l="${label}" '$2==l{print $1; found=1} END{exit !found}' "${CHECKSUMS}") || {
		echo "ERROR: no golden checksum recorded for '${label}' -- run rust/scripts/generate-golden.sh" >&2
		exit 1
	}
	printf '%s' "${hash}"
}

check() {
	# check <file> <label> <description> -- hashes `file` and compares
	# against the golden checksum recorded for `label`.
	local file="$1" label="$2" desc="$3" want got
	want="$(golden_hash_of "${label}")"
	got="$(sha256_of "${file}")"
	if [ "${want}" = "${got}" ]; then
		echo "PASS  ${desc}: matches golden checksum"
	else
		echo "FAIL  ${desc}: does not match golden checksum"
		fail=1
	fi
}

# Dumps `in` and checks against the golden ${name}.json checksum, then
# builds from the GOLDEN json (not the just-produced dump, so a dump
# regression and a build regression are reported independently) and checks
# against the golden ${name}.${ext} checksum. The build step needs the
# dump's actual bytes as input, not just its hash, so it re-dumps rather
# than trying to reuse a hash-verified-but-discarded copy.
compare_payload() {
	local name="$1" ext="$2" in="$3"

	rm -f "${BUILD}/${name}.json"
	if ! "${RUST_BIN}/otfccdump" "${in}" -o "${BUILD}/${name}.json" --pretty; then
		echo "FAIL  ${name} dump: Rust otfccdump exited non-zero"
		fail=1
		return
	fi
	check "${BUILD}/${name}.json" "${name}.json" "${name} dump"

	rm -f "${BUILD}/${name}.${ext}"
	if ! "${RUST_BIN}/otfccbuild" "${BUILD}/${name}.json" -o "${BUILD}/${name}.${ext}" --keep-average-char-width --keep-modified-time; then
		echo "FAIL  ${name}.${ext}: Rust otfccbuild exited non-zero"
		fail=1
		return
	fi
	check "${BUILD}/${name}.${ext}" "${name}.${ext}" "${name}.${ext}"
}

echo "==> Comparing Rust output against golden checksums (tests/golden/checksums.sha256)"
compare_payload NotoNastaliqUrdu-Regular ttf tests/payload/NotoNastaliqUrdu-Regular.ttf
compare_payload iosevka-r ttf tests/payload/iosevka-r.ttf
compare_payload BungeeColor-Regular_colr_Windows ttf tests/payload/BungeeColor-Regular_colr_Windows.ttf
compare_payload Reinebow-SVGinOT ttf tests/payload/Reinebow-SVGinOT.ttf
compare_payload vtt ttf tests/payload/vtt.ttf
compare_payload Molengo-Regular ttf tests/payload/Molengo-Regular.ttf
compare_payload KRName-Regular otf tests/payload/KRName-Regular.otf
# gvar-test.ttf is itself a frozen fixture (tests/payload/gvar-test.ttf, not
# regenerated by fontTools at test time): fontTools' FontBuilder stamps
# head.created/modified with the current wall-clock time when it isn't set
# explicitly, which would make a freshly-generated copy differ from the
# golden dump in those two fields alone, on every run, for no real reason.
compare_payload gvar-test ttf tests/payload/gvar-test.ttf

# A lookup type otfcc does not recognise is *kept*, not clamped (see
# compare-with-c.sh for the full explanation). Dump only: both toolchains
# refuse to build the resulting JSON, so there is nothing to build-compare.
if command -v python3 >/dev/null 2>&1; then
	UNKNOWN_LOOKUP="${BUILD}/unknown-lookup.ttf"
	python3 rust/scripts/make-test-unknown-lookup.py tests/payload/iosevka-r.ttf "${UNKNOWN_LOOKUP}"
	rm -f "${BUILD}/unknown-lookup.json"
	if ! "${RUST_BIN}/otfccdump" "${UNKNOWN_LOOKUP}" -o "${BUILD}/unknown-lookup.json" --pretty; then
		echo "FAIL  unknown-lookup dump: Rust otfccdump exited non-zero"
		fail=1
	else
		check "${BUILD}/unknown-lookup.json" "unknown-lookup.json" "unknown-lookup dump"
	fi
else
	echo "  (skipping unknown-lookup: python3 not found)"
fi

# meta-test / vdmx-test: the synthetic input JSON is regenerated fresh each
# run (both generator scripts are pure byte-patchers over the iosevka-r
# dump, no wall-clock input, so this is deterministic) and then build +
# dump-of-build are checked against golden the same as any other payload.
synth_payload() {
	local name="$1" maker="$2"
	if ! command -v python3 >/dev/null 2>&1; then
		echo "  (skipping ${name}: python3 not found)"
		return
	fi
	local input="${BUILD}/${name}-input.json"
	python3 "${maker}" "${BUILD}/iosevka-r.json" "${input}"

	rm -f "${BUILD}/${name}.ttf"
	if ! "${RUST_BIN}/otfccbuild" "${input}" -o "${BUILD}/${name}.ttf" --keep-average-char-width --keep-modified-time; then
		echo "FAIL  ${name}.ttf: Rust otfccbuild exited non-zero"
		fail=1
		return
	fi
	check "${BUILD}/${name}.ttf" "${name}.ttf" "${name}.ttf"

	rm -f "${BUILD}/${name}.dump.json"
	if ! "${RUST_BIN}/otfccdump" "${BUILD}/${name}.ttf" -o "${BUILD}/${name}.dump.json" --pretty; then
		echo "FAIL  ${name} dump: Rust otfccdump exited non-zero"
		fail=1
	else
		check "${BUILD}/${name}.dump.json" "${name}.dump.json" "${name} dump"
	fi
}
synth_payload meta-test rust/scripts/make-test-meta.py
synth_payload vdmx-test rust/scripts/make-test-vdmx.py
synth_payload gsub-multi-dedup rust/scripts/make-test-gsub-multi-dedup.py
synth_payload gpos-single-dedup rust/scripts/make-test-gpos-single-dedup.py
synth_payload gpos-cursive-dedup rust/scripts/make-test-gpos-cursive-dedup.py

echo "==> Comparing Rust otfccdll (cdylib) output against golden"
RUST_SO_EXT="so"
[ "$(uname)" = "Darwin" ] && RUST_SO_EXT="dylib"
DLL_RUST="${RUST_BIN}/libotfcc_rust.${RUST_SO_EXT}"

. "$(dirname "$0")/dll-arch-check.sh"
DLL_ARCH_SKIP="$(dll_arch_skip_reason "${DLL_RUST}")"

if [ -n "${DLL_ARCH_SKIP}" ]; then
	echo "  (SKIP otfccdll comparison: ${DLL_ARCH_SKIP})"
elif [ -f "${DLL_RUST}" ]; then
	# The DLL API doesn't take --keep-modified-time, so
	# head.created/modified/checkSumAdjustment legitimately vary run to
	# run -- even two same-library invocations differ at those bytes (see
	# compare-with-c.sh). A same-run baseline (two fresh builds, diffed
	# against each other) is *not* a reliable tolerance here the way it was
	# in compare-with-c.sh: those two builds can land in the same
	# wall-clock second and diff by 0 bytes, while the golden fixture was
	# captured at a different, arbitrary time and legitimately diffs by a
	# handful of timestamp bytes even from perfectly correct output. Use a
	# fixed cap instead, generous enough for every timestamp/checksum field
	# in the format (created + modified LONGDATETIMEs, checkSumAdjustment)
	# to differ, but far too small for any real structural difference. This
	# is also why dll-test.otf is a real committed file, not a checksum --
	# a hash can't express "close enough".
	TOLERANCE=32
	python3 "$(dirname "$0")/test-dll.py" "${DLL_RUST}" "${BUILD}/Molengo-Regular.json" "${BUILD}/dll-rust-1.otf"
	golden_diff=$( (cmp -l "${GOLDEN}/dll-test.otf" "${BUILD}/dll-rust-1.otf" 2>/dev/null || true) | wc -l | tr -d ' ')
	if [ "${golden_diff}" -le "${TOLERANCE}" ]; then
		echo "PASS  otfccdll: matches golden (differs in ${golden_diff} bytes, within the ${TOLERANCE}-byte timestamp tolerance)"
	else
		echo "FAIL  otfccdll: differs from golden in ${golden_diff} bytes (expected at most ${TOLERANCE}, timestamp-only)"
		fail=1
	fi
else
	echo "  (skipping otfccdll comparison: ${DLL_RUST} not built)"
fi

if [ "${fail}" -ne 0 ]; then
	echo "==> FAILED: at least one payload's Rust output differs from the golden checksums" >&2
	exit 1
fi
echo "==> All payloads match the golden checksums"
