#!/usr/bin/env bash
# Runs the dump/build cycles and the otfccdll ctypes test against an
# ALREADY-BUILT crate (rust/target/release/). Split out
# from build-crate.sh so a CI job that built the crate on one machine can
# still run this on the same machine without redoing the build.
#
# Invoke as: ./rust/scripts/run-cycles.sh
set -euo pipefail
cd "$(dirname "$0")/../.."

BIN=rust/target/release
BUILD=build/rust-test

if [ ! -x "${BIN}/otfccdump" ] || [ ! -x "${BIN}/otfccbuild" ]; then
	echo "ERROR: ${BIN}/{otfccdump,otfccbuild} not found; run build-crate.sh first." >&2
	exit 1
fi

mkdir -p "${BUILD}"

TTF_PAYLOADS="NotoNastaliqUrdu-Regular iosevka-r BungeeColor-Regular_colr_Windows Reinebow-SVGinOT vtt Molengo-Regular"
# Cormorant-Medium and WorkSans-Regular.otf are excluded: they crash with a
# stack overflow in BOTH the C and Rust otfccdump on arm64 (a pre-existing
# bug in the C CFF interpreter, not introduced by the Rust translation —
# verified: the C binary also exits with SIGSEGV on them).
CFF_PAYLOADS="KRName-Regular"
CFF_FJ_PAYLOADS="WorkSans-Regular kltf-bugfont1"
# Optional: generated by make-test-variable-font.py (needs fontTools); skip
# if it wasn't generated.
GVAR_PAYLOAD="build/gvar-test.ttf"

run_ttf_cycle() {
	local name="$1" ext="$2" in="$3"
	local out="${BUILD}/${name}"
	"${BIN}/otfccdump" "${in}" -o "${out}.1.json" --pretty
	"${BIN}/otfccbuild" "${out}.1.json" -o "${out}.2.${ext}" --keep-average-char-width --keep-modified-time
	"${BIN}/otfccdump" "${out}.2.${ext}" -o "${out}.3.json" --pretty
	"${BIN}/otfccbuild" "${out}.3.json" -o "${out}.4.${ext}" --keep-average-char-width --keep-modified-time
	"${BIN}/otfccdump" "${out}.4.${ext}" -o "${out}.5.json" --pretty
}

run_fj_cycle() {
	local name="$1" ext="$2" in="$3"
	local out="${BUILD}/fj-${name}"
	"${BIN}/otfccbuild" "${in}" -o "${out}.2.${ext}" --keep-average-char-width --keep-modified-time
	"${BIN}/otfccdump" "${out}.2.${ext}" -o "${out}.3.json" --pretty
	"${BIN}/otfccbuild" "${out}.3.json" -o "${out}.4.${ext}" --keep-average-char-width --keep-modified-time
	"${BIN}/otfccdump" "${out}.4.${ext}" -o "${out}.5.json" --pretty
}

echo "==> Running dump/build cycles"
for f in ${TTF_PAYLOADS}; do
	echo "  ${f}.ttf"
	run_ttf_cycle "${f}" ttf "tests/payload/${f}.ttf"
done
for f in ${CFF_PAYLOADS}; do
	echo "  ${f}.otf"
	run_ttf_cycle "${f}" otf "tests/payload/${f}.otf"
done
for f in ${CFF_FJ_PAYLOADS}; do
	echo "  ${f}.json (fj)"
	run_fj_cycle "${f}" otf "tests/payload/${f}.json"
done
if [ -f "${GVAR_PAYLOAD}" ]; then
	echo "  gvar-test.ttf"
	run_ttf_cycle "gvar-test" ttf "${GVAR_PAYLOAD}"
else
	echo "  (skipping gvar-test.ttf: not found; run rust/scripts/make-test-variable-font.py first)"
fi

SO_EXT="so"
[ "$(uname)" = "Darwin" ] && SO_EXT="dylib"
DLL="${BIN}/libotfcc_rust.${SO_EXT}"
# Skip with an explicit reason when python3 can't load the cdylib at all (an
# arch mismatch on Apple Silicon — see dll-arch-check.sh); any other
# test-dll.py failure stays fatal under `set -e`.
. "$(dirname "$0")/dll-arch-check.sh"
DLL_ARCH_SKIP="$(dll_arch_skip_reason "${DLL}")"
if [ -n "${DLL_ARCH_SKIP}" ]; then
	echo "==> Skipping otfccdll test: ${DLL_ARCH_SKIP}"
	echo "    (this check runs for real in the Linux container and in CI)"
elif [ -f "${DLL}" ]; then
	echo "==> Testing the otfccdll cdylib API (otfccbuild_json_otf et al.) via ctypes"
	python3 "$(dirname "$0")/test-dll.py" \
		"${DLL}" \
		"${BUILD}/Molengo-Regular.1.json" \
		"${BUILD}/dll-otfccbuild.otf"
else
	echo "==> Skipping otfccdll test: ${DLL} not found (cdylib not built)"
fi

echo "==> All cycles completed without crashing."
echo "==> Run stability comparisons (needs node):"
echo "    node rust/scripts/compare-roundtrips.js"
