pub const NULL: *mut ::core::ffi::c_void = ::core::ptr::null_mut::<::core::ffi::c_void>();
#[no_mangle]
pub static mut SCRIPT_LANGUAGE_SEPARATOR: ::core::ffi::c_char = '_' as i32 as ::core::ffi::c_char;
#[no_mangle]
pub static mut lookupFlagsLabels: [*const ::core::ffi::c_char; 5] = [
    b"rightToLeft\0" as *const u8 as *const ::core::ffi::c_char,
    b"ignoreBases\0" as *const u8 as *const ::core::ffi::c_char,
    b"ignoreLigatures\0" as *const u8 as *const ::core::ffi::c_char,
    b"ignoreMarks\0" as *const u8 as *const ::core::ffi::c_char,
    ::core::ptr::null::<::core::ffi::c_char>(),
];
#[no_mangle]
pub static mut tableNames: [*const ::core::ffi::c_char; 42] = [
    b"unknown\0" as *const u8 as *const ::core::ffi::c_char,
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    b"gsub_unknown\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_single\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_multiple\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_alternate\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_ligature\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_context\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_chaining\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_extend\0" as *const u8 as *const ::core::ffi::c_char,
    b"gsub_reverse\0" as *const u8 as *const ::core::ffi::c_char,
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    ::core::ptr::null::<::core::ffi::c_char>(),
    b"gpos_unknown\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_single\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_pair\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_cursive\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_mark_to_base\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_mark_to_ligature\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_mark_to_mark\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_context\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_chaining\0" as *const u8 as *const ::core::ffi::c_char,
    b"gpos_extend\0" as *const u8 as *const ::core::ffi::c_char,
];
