//! Rust-native replacement for `scripts/compare-with-golden.sh` (see
//! that script's own header for the full history/rationale). Builds each
//! payload with the just-compiled `otfccdump`/`otfccbuild` and checks the
//! SHA-256 of the output against `tests/golden/checksums.sha256`, the
//! frozen snapshot that used to be validated against the C toolchain (see
//! `RUST_MIGRATION.md`).
//!
//! The `otfccdll` (cdylib) comparison and the Python-generated `unknown-
//! lookup`/dedup-fixture synthetic payloads are **not** included here --
//! see the plan doc's Stage F: the cdylib check is Phase 5 (needs
//! `libloading`, a bigger self-contained piece), and the Python fixture
//! generators (`make-test-*.py`) stay as external dev tooling by explicit
//! plan decision (low migration value, `std::process::Command`-invoked
//! from here rather than ported).

mod support;

use std::collections::HashMap;
use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use support::{
    check_against_golden, golden_checksums, otfccbuild, otfccdump, payload, run_ok, scratch_dir,
};

/// Each test gets its own scratch subdirectory: `cargo test` runs the
/// tests in this file in parallel, and a shared directory let one test
/// delete or rewrite an intermediate file (`iosevka-r.json`,
/// `KRName-Regular.json`) while another was reading it.
fn build_dir(test: &str) -> PathBuf {
    scratch_dir(&format!("compare-with-golden-rs/{test}"))
}

/// Dumps `input` to `{name}.json` under `build`, replacing any copy left
/// by an earlier run, and returns its path.
fn dump_fresh(build: &Path, name: &str, input: &Path) -> PathBuf {
    let json_path = build.join(format!("{name}.json"));
    let _ = std::fs::remove_file(&json_path);
    run_ok(
        &format!("{name} dump"),
        &otfccdump(),
        &[input.as_os_str(), OsStr::new("-o"), json_path.as_os_str(), OsStr::new("--pretty")],
    );
    json_path
}

/// Dumps `input` and checks against the golden `{name}.json` checksum,
/// then builds from the GOLDEN json (not the just-produced dump, so a dump
/// regression and a build regression are reported independently) and
/// checks against the golden `{name}.{ext}` checksum -- same two-step
/// shape as the shell script's own `compare_payload`.
fn compare_payload(
    build: &Path,
    name: &str,
    ext: &str,
    input: &Path,
    checksums: &HashMap<String, String>,
    errors: &mut Vec<String>,
) {
    let json_path = dump_fresh(build, name, input);
    if let Err(e) = check_against_golden(&json_path, &format!("{name}.json"), checksums) {
        errors.push(e);
    }

    let out_path = build.join(format!("{name}.{ext}"));
    let _ = std::fs::remove_file(&out_path);
    run_ok(
        &format!("{name}.{ext} build"),
        &otfccbuild(),
        &[
            json_path.as_os_str(),
            OsStr::new("-o"),
            out_path.as_os_str(),
            OsStr::new("--keep-average-char-width"),
            OsStr::new("--keep-modified-time"),
        ],
    );
    if let Err(e) = check_against_golden(&out_path, &format!("{name}.{ext}"), checksums) {
        errors.push(e);
    }
}

#[test]
fn fixed_payloads_match_golden() {
    let checksums = golden_checksums();
    let build = build_dir("fixed-payloads");
    let mut errors = Vec::new();

    let payloads: &[(&str, &str, &str)] = &[
        ("NotoNastaliqUrdu-Regular", "ttf", "NotoNastaliqUrdu-Regular.ttf"),
        ("iosevka-r", "ttf", "iosevka-r.ttf"),
        ("BungeeColor-Regular_colr_Windows", "ttf", "BungeeColor-Regular_colr_Windows.ttf"),
        ("Reinebow-SVGinOT", "ttf", "Reinebow-SVGinOT.ttf"),
        ("vtt", "ttf", "vtt.ttf"),
        ("Molengo-Regular", "ttf", "Molengo-Regular.ttf"),
        ("KRName-Regular", "otf", "KRName-Regular.otf"),
        // CFF fonts with more than 107 subroutines, so they call the lower
        // ones with negative numbers (KRName has fewer and never does).
        ("WorkSans-Regular", "otf", "WorkSans-Regular.otf"),
        // CID-keyed, with a Private DICT and local subroutines per FD.
        ("FDArrayTest257", "otf", "FDArrayTest257.otf"),
        // gvar-test.ttf is itself a frozen fixture, not regenerated by
        // fontTools at test time: fontTools' FontBuilder stamps
        // head.created/modified with the current wall-clock time when
        // it isn't set explicitly, which would make a freshly-generated
        // copy differ from the golden dump in those two fields alone,
        // on every run, for no real reason.
        ("gvar-test", "ttf", "gvar-test.ttf"),
    ];
    for (name, ext, input_file) in payloads {
        compare_payload(&build, name, ext, &payload(input_file), &checksums, &mut errors);
    }

    assert!(errors.is_empty(), "{} payload(s) failed:\n{}", errors.len(), errors.join("\n"));
}

/// The checksums above pin the dump, but not whether it is right. This pins
/// one glyph against an independent reader: WorkSans-Regular's `I` is
/// `-348 0 660 -33 callsubr vstem 188 660 -14 callsubr endchar`, and these
/// are the points fontTools draws for it. Before subroutine numbers were
/// read as signed, both calls went to the subroutine at the bias and `I`
/// came out as two stray accent-shaped contours.
#[test]
fn worksans_negative_subroutine_numbers_draw_the_fonttools_outline() {
    let build = build_dir("worksans-outline");
    let json_path = dump_fresh(&build, "WorkSans-Regular", &payload("WorkSans-Regular.otf"));
    // The name table holds Latin-1 bytes, which the dump writes through raw.
    let bytes = std::fs::read(&json_path).expect("read WorkSans-Regular.json");
    let font: serde_json::Value = serde_json::from_str(&String::from_utf8_lossy(&bytes))
        .expect("parse WorkSans-Regular.json");
    let contours: Vec<Vec<(i64, i64, bool)>> = font["glyf"]["I"]["contours"]
        .as_array()
        .expect("glyph I has contours")
        .iter()
        .map(|contour| {
            contour
                .as_array()
                .expect("contour is an array")
                .iter()
                .map(|p| (p["x"].as_i64().unwrap(), p["y"].as_i64().unwrap(), p["on"].as_bool().unwrap()))
                .collect()
        })
        .collect();
    assert_eq!(
        contours,
        vec![vec![(188, 660, true), (108, 660, true), (108, 0, true), (188, 0, true)]]
    );
}

#[test]
fn krname_cff_subroutinize_o2_matches_golden() {
    // CFF subroutinization (-O2), built from this test's own fresh dump of
    // KRName-Regular.otf (fixed_payloads_match_golden checks that dump
    // against golden).
    let checksums = golden_checksums();
    let build = build_dir("krname-o2");
    let json_path = dump_fresh(&build, "KRName-Regular", &payload("KRName-Regular.otf"));

    let out_path = build.join("KRName-Regular-O2.otf");
    let _ = std::fs::remove_file(&out_path);
    run_ok(
        "KRName-Regular-O2.otf build",
        &otfccbuild(),
        &[
            json_path.as_os_str(),
            OsStr::new("-o"),
            out_path.as_os_str(),
            OsStr::new("-O2"),
            OsStr::new("-k"),
            OsStr::new("--keep-modified-time"),
        ],
    );
    check_against_golden(&out_path, "KRName-Regular-O2.otf", &checksums).unwrap_or_else(|e| panic!("{e}"));
}

/// `true` (and prints why) if `python3` isn't on PATH -- the shell script
/// this replaces skips its Python-dependent checks the same way, rather
/// than failing the whole comparison in an environment without Python.
fn skip_if_no_python3(check_name: &str) -> bool {
    let has_python3 = std::process::Command::new("python3")
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !has_python3 {
        eprintln!("  (skipping {check_name}: python3 not found)");
    }
    !has_python3
}

#[test]
fn unknown_lookup_dump_matches_golden() {
    // A lookup type otfcc does not recognise is *kept*, not clamped -- see
    // make-test-unknown-lookup.py's own header. Dump only: otfccbuild
    // refuses to build the resulting JSON, so there is nothing to
    // build-compare.
    if skip_if_no_python3("unknown-lookup") {
        return;
    }
    let checksums = golden_checksums();
    let build = build_dir("unknown-lookup");
    let ttf_path = build.join("unknown-lookup.ttf");
    run_ok(
        "make-test-unknown-lookup.py",
        Path::new("python3"),
        &[
            support::repo_root().join("scripts/make-test-unknown-lookup.py").as_os_str(),
            payload("iosevka-r.ttf").as_os_str(),
            ttf_path.as_os_str(),
        ],
    );
    let json_path = build.join("unknown-lookup.json");
    let _ = std::fs::remove_file(&json_path);
    run_ok(
        "unknown-lookup dump",
        &otfccdump(),
        &[ttf_path.as_os_str(), OsStr::new("-o"), json_path.as_os_str(), OsStr::new("--pretty")],
    );
    check_against_golden(&json_path, "unknown-lookup.json", &checksums).unwrap_or_else(|e| panic!("{e}"));
}

/// `synth_payload <name> <maker.py>`: the maker script patches
/// `iosevka-r.json` into a synthetic input, which is built and then
/// dump-of-build is checked against golden -- same shape as the shell
/// script's own `synth_payload`.
fn synth_payload(
    build: &Path,
    iosevka_json: &Path,
    name: &str,
    maker_script: &str,
    checksums: &HashMap<String, String>,
    errors: &mut Vec<String>,
) {
    let input_path = build.join(format!("{name}-input.json"));
    run_ok(
        &format!("{maker_script} (for {name})"),
        Path::new("python3"),
        &[
            support::repo_root().join(maker_script).as_os_str(),
            iosevka_json.as_os_str(),
            input_path.as_os_str(),
        ],
    );

    let ttf_path = build.join(format!("{name}.ttf"));
    let _ = std::fs::remove_file(&ttf_path);
    run_ok(
        &format!("{name}.ttf build"),
        &otfccbuild(),
        &[
            input_path.as_os_str(),
            OsStr::new("-o"),
            ttf_path.as_os_str(),
            OsStr::new("--keep-average-char-width"),
            OsStr::new("--keep-modified-time"),
        ],
    );
    if let Err(e) = check_against_golden(&ttf_path, &format!("{name}.ttf"), checksums) {
        errors.push(e);
    }

    let dump_json_path = build.join(format!("{name}.dump.json"));
    let _ = std::fs::remove_file(&dump_json_path);
    run_ok(
        &format!("{name} dump"),
        &otfccdump(),
        &[ttf_path.as_os_str(), OsStr::new("-o"), dump_json_path.as_os_str(), OsStr::new("--pretty")],
    );
    if let Err(e) = check_against_golden(&dump_json_path, &format!("{name}.dump.json"), checksums) {
        errors.push(e);
    }
}

#[test]
fn synthetic_dedup_and_table_payloads_match_golden() {
    if skip_if_no_python3("synthetic dedup/table payloads") {
        return;
    }
    let checksums = golden_checksums();
    let build = build_dir("synthetic");
    // The makers' shared input. Not checked against golden here --
    // fixed_payloads_match_golden already checks iosevka-r.json.
    let iosevka_json = dump_fresh(&build, "iosevka-r", &payload("iosevka-r.ttf"));
    let mut errors = Vec::new();

    let synths: &[(&str, &str)] = &[
        ("meta-test", "scripts/make-test-meta.py"),
        ("vdmx-test", "scripts/make-test-vdmx.py"),
        ("gsub-multi-dedup", "scripts/make-test-gsub-multi-dedup.py"),
        ("gpos-single-dedup", "scripts/make-test-gpos-single-dedup.py"),
        ("gpos-cursive-dedup", "scripts/make-test-gpos-cursive-dedup.py"),
        ("gdef-ligcaret-dedup", "scripts/make-test-gdef-ligcaret-dedup.py"),
        ("gsub-single-dedup", "scripts/make-test-gsub-single-dedup.py"),
        ("gsub-reverse-dedup", "scripts/make-test-gsub-reverse-dedup.py"),
        ("mark-consolidate-dedup", "scripts/make-test-mark-consolidate-dedup.py"),
    ];
    for (name, maker) in synths {
        synth_payload(&build, &iosevka_json, name, maker, &checksums, &mut errors);
    }

    assert!(errors.is_empty(), "{} synthetic payload(s) failed:\n{}", errors.len(), errors.join("\n"));
}
