//! Rust-native replacement for `rust/scripts/compare-with-golden.sh` (see
//! that script's own header for the full history/rationale). Builds each
//! payload with the just-compiled `otfccdump`/`otfccbuild` and checks the
//! SHA-256 of the output against `tests/golden/checksums.sha256`, the
//! frozen snapshot that used to be validated against the C toolchain (see
//! `rust/README.md`).
//!
//! The `otfccdll` (cdylib) comparison and the Python-generated `unknown-
//! lookup`/dedup-fixture synthetic payloads are **not** included here --
//! see the plan doc's Stage F: the cdylib check is Phase 5 (needs
//! `libloading`, a bigger self-contained piece), and the Python fixture
//! generators (`make-test-*.py`) stay as external dev tooling by explicit
//! plan decision (low migration value, `std::process::Command`-invoked
//! from here rather than ported).

mod support;

use std::collections::HashMap;
use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use support::{
    check_against_golden, golden_checksums, otfccbuild, otfccdump, payload, run_ok, scratch_dir,
};

fn build_dir() -> PathBuf {
    scratch_dir("compare-with-golden-rs")
}

/// Dumps `input` and checks against the golden `{name}.json` checksum,
/// then builds from the GOLDEN json (not the just-produced dump, so a dump
/// regression and a build regression are reported independently) and
/// checks against the golden `{name}.{ext}` checksum -- same two-step
/// shape as the shell script's own `compare_payload`.
fn compare_payload(name: &str, ext: &str, input: &Path, checksums: &HashMap<String, String>, errors: &mut Vec<String>) {
    let build = build_dir();
    let json_path = build.join(format!("{name}.json"));
    let _ = std::fs::remove_file(&json_path);
    run_ok(
        &format!("{name} dump"),
        &otfccdump(),
        &[input.as_os_str(), OsStr::new("-o"), json_path.as_os_str(), OsStr::new("--pretty")],
    );
    if let Err(e) = check_against_golden(&json_path, &format!("{name}.json"), checksums) {
        errors.push(e);
    }

    let out_path = build.join(format!("{name}.{ext}"));
    let _ = std::fs::remove_file(&out_path);
    run_ok(
        &format!("{name}.{ext} build"),
        &otfccbuild(),
        &[
            json_path.as_os_str(),
            OsStr::new("-o"),
            out_path.as_os_str(),
            OsStr::new("--keep-average-char-width"),
            OsStr::new("--keep-modified-time"),
        ],
    );
    if let Err(e) = check_against_golden(&out_path, &format!("{name}.{ext}"), checksums) {
        errors.push(e);
    }
}

#[test]
fn fixed_payloads_match_golden() {
    let checksums = golden_checksums();
    let mut errors = Vec::new();

    let payloads: &[(&str, &str, &str)] = &[
        ("NotoNastaliqUrdu-Regular", "ttf", "NotoNastaliqUrdu-Regular.ttf"),
        ("iosevka-r", "ttf", "iosevka-r.ttf"),
        ("BungeeColor-Regular_colr_Windows", "ttf", "BungeeColor-Regular_colr_Windows.ttf"),
        ("Reinebow-SVGinOT", "ttf", "Reinebow-SVGinOT.ttf"),
        ("vtt", "ttf", "vtt.ttf"),
        ("Molengo-Regular", "ttf", "Molengo-Regular.ttf"),
        ("KRName-Regular", "otf", "KRName-Regular.otf"),
        // gvar-test.ttf is itself a frozen fixture, not regenerated by
        // fontTools at test time: fontTools' FontBuilder stamps
        // head.created/modified with the current wall-clock time when
        // it isn't set explicitly, which would make a freshly-generated
        // copy differ from the golden dump in those two fields alone,
        // on every run, for no real reason.
        ("gvar-test", "ttf", "gvar-test.ttf"),
    ];
    for (name, ext, input_file) in payloads {
        compare_payload(name, ext, &payload(input_file), &checksums, &mut errors);
    }

    assert!(errors.is_empty(), "{} payload(s) failed:\n{}", errors.len(), errors.join("\n"));
}

#[test]
fn krname_cff_subroutinize_o2_matches_golden() {
    // CFF subroutinization (-O2): reuses the KRName-Regular.json the
    // fixed_payloads test produces -- if that test hasn't run yet in this
    // process, produce it fresh here too (cargo test runs test fns in
    // parallel/any order, so this can't assume the other test already ran).
    let checksums = golden_checksums();
    let build = build_dir();
    let json_path = build.join("KRName-Regular.json");
    if !json_path.exists() {
        run_ok(
            "KRName-Regular dump (for -O2)",
            &otfccdump(),
            &[
                payload("KRName-Regular.otf").as_os_str(),
                OsStr::new("-o"),
                json_path.as_os_str(),
                OsStr::new("--pretty"),
            ],
        );
    }

    let out_path = build.join("KRName-Regular-O2.otf");
    let _ = std::fs::remove_file(&out_path);
    run_ok(
        "KRName-Regular-O2.otf build",
        &otfccbuild(),
        &[
            json_path.as_os_str(),
            OsStr::new("-o"),
            out_path.as_os_str(),
            OsStr::new("-O2"),
            OsStr::new("-k"),
            OsStr::new("--keep-modified-time"),
        ],
    );
    check_against_golden(&out_path, "KRName-Regular-O2.otf", &checksums).unwrap_or_else(|e| panic!("{e}"));
}

/// `true` (and prints why) if `python3` isn't on PATH -- the shell script
/// this replaces skips its Python-dependent checks the same way, rather
/// than failing the whole comparison in an environment without Python.
fn skip_if_no_python3(check_name: &str) -> bool {
    let has_python3 = std::process::Command::new("python3")
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !has_python3 {
        eprintln!("  (skipping {check_name}: python3 not found)");
    }
    !has_python3
}

fn ensure_iosevka_r_json(build: &Path, checksums: &HashMap<String, String>) -> PathBuf {
    let json_path = build.join("iosevka-r.json");
    if !json_path.exists() {
        run_ok(
            "iosevka-r dump (for synthetic payloads)",
            &otfccdump(),
            &[
                payload("iosevka-r.ttf").as_os_str(),
                OsStr::new("-o"),
                json_path.as_os_str(),
                OsStr::new("--pretty"),
            ],
        );
        // Not asserted here -- fixed_payloads_match_golden already checks
        // iosevka-r.json against golden; this fn's only job is to make sure
        // the file exists as an *input* for the synthetic-payload makers.
        let _ = check_against_golden(&json_path, "iosevka-r.json", checksums);
    }
    json_path
}

#[test]
fn unknown_lookup_dump_matches_golden() {
    // A lookup type otfcc does not recognise is *kept*, not clamped -- see
    // make-test-unknown-lookup.py's own header. Dump only: otfccbuild
    // refuses to build the resulting JSON, so there is nothing to
    // build-compare.
    if skip_if_no_python3("unknown-lookup") {
        return;
    }
    let checksums = golden_checksums();
    let build = build_dir();
    let ttf_path = build.join("unknown-lookup.ttf");
    run_ok(
        "make-test-unknown-lookup.py",
        Path::new("python3"),
        &[
            support::repo_root().join("rust/scripts/make-test-unknown-lookup.py").as_os_str(),
            payload("iosevka-r.ttf").as_os_str(),
            ttf_path.as_os_str(),
        ],
    );
    let json_path = build.join("unknown-lookup.json");
    let _ = std::fs::remove_file(&json_path);
    run_ok(
        "unknown-lookup dump",
        &otfccdump(),
        &[ttf_path.as_os_str(), OsStr::new("-o"), json_path.as_os_str(), OsStr::new("--pretty")],
    );
    check_against_golden(&json_path, "unknown-lookup.json", &checksums).unwrap_or_else(|e| panic!("{e}"));
}

/// `synth_payload <name> <maker.py>`: the maker script patches
/// `iosevka-r.json` into a synthetic input, which is built and then
/// dump-of-build is checked against golden -- same shape as the shell
/// script's own `synth_payload`.
fn synth_payload(name: &str, maker_script: &str, checksums: &HashMap<String, String>, errors: &mut Vec<String>) {
    let build = build_dir();
    let iosevka_json = ensure_iosevka_r_json(&build, checksums);
    let input_path = build.join(format!("{name}-input.json"));
    run_ok(
        &format!("{maker_script} (for {name})"),
        Path::new("python3"),
        &[
            support::repo_root().join(maker_script).as_os_str(),
            iosevka_json.as_os_str(),
            input_path.as_os_str(),
        ],
    );

    let ttf_path = build.join(format!("{name}.ttf"));
    let _ = std::fs::remove_file(&ttf_path);
    run_ok(
        &format!("{name}.ttf build"),
        &otfccbuild(),
        &[
            input_path.as_os_str(),
            OsStr::new("-o"),
            ttf_path.as_os_str(),
            OsStr::new("--keep-average-char-width"),
            OsStr::new("--keep-modified-time"),
        ],
    );
    if let Err(e) = check_against_golden(&ttf_path, &format!("{name}.ttf"), checksums) {
        errors.push(e);
    }

    let dump_json_path = build.join(format!("{name}.dump.json"));
    let _ = std::fs::remove_file(&dump_json_path);
    run_ok(
        &format!("{name} dump"),
        &otfccdump(),
        &[ttf_path.as_os_str(), OsStr::new("-o"), dump_json_path.as_os_str(), OsStr::new("--pretty")],
    );
    if let Err(e) = check_against_golden(&dump_json_path, &format!("{name}.dump.json"), checksums) {
        errors.push(e);
    }
}

#[test]
fn synthetic_dedup_and_table_payloads_match_golden() {
    if skip_if_no_python3("synthetic dedup/table payloads") {
        return;
    }
    let checksums = golden_checksums();
    let mut errors = Vec::new();

    let synths: &[(&str, &str)] = &[
        ("meta-test", "rust/scripts/make-test-meta.py"),
        ("vdmx-test", "rust/scripts/make-test-vdmx.py"),
        ("gsub-multi-dedup", "rust/scripts/make-test-gsub-multi-dedup.py"),
        ("gpos-single-dedup", "rust/scripts/make-test-gpos-single-dedup.py"),
        ("gpos-cursive-dedup", "rust/scripts/make-test-gpos-cursive-dedup.py"),
        ("gdef-ligcaret-dedup", "rust/scripts/make-test-gdef-ligcaret-dedup.py"),
        ("gsub-single-dedup", "rust/scripts/make-test-gsub-single-dedup.py"),
        ("gsub-reverse-dedup", "rust/scripts/make-test-gsub-reverse-dedup.py"),
        ("mark-consolidate-dedup", "rust/scripts/make-test-mark-consolidate-dedup.py"),
    ];
    for (name, maker) in synths {
        synth_payload(name, maker, &checksums, &mut errors);
    }

    assert!(errors.is_empty(), "{} synthetic payload(s) failed:\n{}", errors.len(), errors.join("\n"));
}
