extern "C" {
    fn sdsnewlen(init: *const ::core::ffi::c_void, initlen: size_t) -> sds;
    fn sdsnew(init: *const ::core::ffi::c_char) -> sds;
}
pub type __uint8_t = u8;
pub type __uint16_t = u16;
pub type __uint32_t = u32;
pub type uint8_t = __uint8_t;
pub type uint16_t = __uint16_t;
pub type uint32_t = __uint32_t;
pub type size_t = usize;
pub type sds = *mut ::core::ffi::c_char;
pub type arity_t = uint32_t;
pub type cff_IndexCountType = ::core::ffi::c_uint;
pub const CFF_INDEX_32: cff_IndexCountType = 1;
pub const CFF_INDEX_16: cff_IndexCountType = 0;
#[derive(Copy, Clone)]
#[repr(C)]
pub struct cff_Index {
    pub countType: cff_IndexCountType,
    pub count: arity_t,
    pub offSize: uint8_t,
    pub offset: *mut uint32_t,
    pub data: *mut uint8_t,
}
pub const NULL: *mut ::core::ffi::c_void = ::core::ptr::null_mut::<::core::ffi::c_void>();
static mut string_standard: [*const ::core::ffi::c_char; 391] = [
    b".notdef\0" as *const u8 as *const ::core::ffi::c_char,
    b"space\0" as *const u8 as *const ::core::ffi::c_char,
    b"exclam\0" as *const u8 as *const ::core::ffi::c_char,
    b"quotedbl\0" as *const u8 as *const ::core::ffi::c_char,
    b"numbersign\0" as *const u8 as *const ::core::ffi::c_char,
    b"dollar\0" as *const u8 as *const ::core::ffi::c_char,
    b"percent\0" as *const u8 as *const ::core::ffi::c_char,
    b"ampersand\0" as *const u8 as *const ::core::ffi::c_char,
    b"quoteright\0" as *const u8 as *const ::core::ffi::c_char,
    b"parenleft\0" as *const u8 as *const ::core::ffi::c_char,
    b"parenright\0" as *const u8 as *const ::core::ffi::c_char,
    b"asterisk\0" as *const u8 as *const ::core::ffi::c_char,
    b"plus\0" as *const u8 as *const ::core::ffi::c_char,
    b"comma\0" as *const u8 as *const ::core::ffi::c_char,
    b"hyphen\0" as *const u8 as *const ::core::ffi::c_char,
    b"period\0" as *const u8 as *const ::core::ffi::c_char,
    b"slash\0" as *const u8 as *const ::core::ffi::c_char,
    b"zero\0" as *const u8 as *const ::core::ffi::c_char,
    b"one\0" as *const u8 as *const ::core::ffi::c_char,
    b"two\0" as *const u8 as *const ::core::ffi::c_char,
    b"three\0" as *const u8 as *const ::core::ffi::c_char,
    b"four\0" as *const u8 as *const ::core::ffi::c_char,
    b"five\0" as *const u8 as *const ::core::ffi::c_char,
    b"six\0" as *const u8 as *const ::core::ffi::c_char,
    b"seven\0" as *const u8 as *const ::core::ffi::c_char,
    b"eight\0" as *const u8 as *const ::core::ffi::c_char,
    b"nine\0" as *const u8 as *const ::core::ffi::c_char,
    b"colon\0" as *const u8 as *const ::core::ffi::c_char,
    b"semicolon\0" as *const u8 as *const ::core::ffi::c_char,
    b"less\0" as *const u8 as *const ::core::ffi::c_char,
    b"equal\0" as *const u8 as *const ::core::ffi::c_char,
    b"greater\0" as *const u8 as *const ::core::ffi::c_char,
    b"question\0" as *const u8 as *const ::core::ffi::c_char,
    b"at\0" as *const u8 as *const ::core::ffi::c_char,
    b"A\0" as *const u8 as *const ::core::ffi::c_char,
    b"B\0" as *const u8 as *const ::core::ffi::c_char,
    b"C\0" as *const u8 as *const ::core::ffi::c_char,
    b"D\0" as *const u8 as *const ::core::ffi::c_char,
    b"E\0" as *const u8 as *const ::core::ffi::c_char,
    b"F\0" as *const u8 as *const ::core::ffi::c_char,
    b"G\0" as *const u8 as *const ::core::ffi::c_char,
    b"H\0" as *const u8 as *const ::core::ffi::c_char,
    b"I\0" as *const u8 as *const ::core::ffi::c_char,
    b"J\0" as *const u8 as *const ::core::ffi::c_char,
    b"K\0" as *const u8 as *const ::core::ffi::c_char,
    b"L\0" as *const u8 as *const ::core::ffi::c_char,
    b"M\0" as *const u8 as *const ::core::ffi::c_char,
    b"N\0" as *const u8 as *const ::core::ffi::c_char,
    b"O\0" as *const u8 as *const ::core::ffi::c_char,
    b"P\0" as *const u8 as *const ::core::ffi::c_char,
    b"Q\0" as *const u8 as *const ::core::ffi::c_char,
    b"R\0" as *const u8 as *const ::core::ffi::c_char,
    b"S\0" as *const u8 as *const ::core::ffi::c_char,
    b"T\0" as *const u8 as *const ::core::ffi::c_char,
    b"U\0" as *const u8 as *const ::core::ffi::c_char,
    b"V\0" as *const u8 as *const ::core::ffi::c_char,
    b"W\0" as *const u8 as *const ::core::ffi::c_char,
    b"X\0" as *const u8 as *const ::core::ffi::c_char,
    b"Y\0" as *const u8 as *const ::core::ffi::c_char,
    b"Z\0" as *const u8 as *const ::core::ffi::c_char,
    b"bracketleft\0" as *const u8 as *const ::core::ffi::c_char,
    b"backslash\0" as *const u8 as *const ::core::ffi::c_char,
    b"bracketright\0" as *const u8 as *const ::core::ffi::c_char,
    b"asciicircum\0" as *const u8 as *const ::core::ffi::c_char,
    b"underscore\0" as *const u8 as *const ::core::ffi::c_char,
    b"quoteleft\0" as *const u8 as *const ::core::ffi::c_char,
    b"a\0" as *const u8 as *const ::core::ffi::c_char,
    b"b\0" as *const u8 as *const ::core::ffi::c_char,
    b"c\0" as *const u8 as *const ::core::ffi::c_char,
    b"d\0" as *const u8 as *const ::core::ffi::c_char,
    b"e\0" as *const u8 as *const ::core::ffi::c_char,
    b"f\0" as *const u8 as *const ::core::ffi::c_char,
    b"g\0" as *const u8 as *const ::core::ffi::c_char,
    b"h\0" as *const u8 as *const ::core::ffi::c_char,
    b"i\0" as *const u8 as *const ::core::ffi::c_char,
    b"j\0" as *const u8 as *const ::core::ffi::c_char,
    b"k\0" as *const u8 as *const ::core::ffi::c_char,
    b"l\0" as *const u8 as *const ::core::ffi::c_char,
    b"m\0" as *const u8 as *const ::core::ffi::c_char,
    b"n\0" as *const u8 as *const ::core::ffi::c_char,
    b"o\0" as *const u8 as *const ::core::ffi::c_char,
    b"p\0" as *const u8 as *const ::core::ffi::c_char,
    b"q\0" as *const u8 as *const ::core::ffi::c_char,
    b"r\0" as *const u8 as *const ::core::ffi::c_char,
    b"s\0" as *const u8 as *const ::core::ffi::c_char,
    b"t\0" as *const u8 as *const ::core::ffi::c_char,
    b"u\0" as *const u8 as *const ::core::ffi::c_char,
    b"v\0" as *const u8 as *const ::core::ffi::c_char,
    b"w\0" as *const u8 as *const ::core::ffi::c_char,
    b"x\0" as *const u8 as *const ::core::ffi::c_char,
    b"y\0" as *const u8 as *const ::core::ffi::c_char,
    b"z\0" as *const u8 as *const ::core::ffi::c_char,
    b"braceleft\0" as *const u8 as *const ::core::ffi::c_char,
    b"bar\0" as *const u8 as *const ::core::ffi::c_char,
    b"braceright\0" as *const u8 as *const ::core::ffi::c_char,
    b"asciitilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"exclamdown\0" as *const u8 as *const ::core::ffi::c_char,
    b"cent\0" as *const u8 as *const ::core::ffi::c_char,
    b"sterling\0" as *const u8 as *const ::core::ffi::c_char,
    b"fraction\0" as *const u8 as *const ::core::ffi::c_char,
    b"yen\0" as *const u8 as *const ::core::ffi::c_char,
    b"florin\0" as *const u8 as *const ::core::ffi::c_char,
    b"section\0" as *const u8 as *const ::core::ffi::c_char,
    b"currency\0" as *const u8 as *const ::core::ffi::c_char,
    b"quotesingle\0" as *const u8 as *const ::core::ffi::c_char,
    b"quotedblleft\0" as *const u8 as *const ::core::ffi::c_char,
    b"guillemotleft\0" as *const u8 as *const ::core::ffi::c_char,
    b"guilsinglleft\0" as *const u8 as *const ::core::ffi::c_char,
    b"guilsinglright\0" as *const u8 as *const ::core::ffi::c_char,
    b"fi\0" as *const u8 as *const ::core::ffi::c_char,
    b"fl\0" as *const u8 as *const ::core::ffi::c_char,
    b"endash\0" as *const u8 as *const ::core::ffi::c_char,
    b"dagger\0" as *const u8 as *const ::core::ffi::c_char,
    b"daggerdbl\0" as *const u8 as *const ::core::ffi::c_char,
    b"periodcentered\0" as *const u8 as *const ::core::ffi::c_char,
    b"paragraph\0" as *const u8 as *const ::core::ffi::c_char,
    b"bullet\0" as *const u8 as *const ::core::ffi::c_char,
    b"quotesinglbase\0" as *const u8 as *const ::core::ffi::c_char,
    b"quotedblbase\0" as *const u8 as *const ::core::ffi::c_char,
    b"quotedblright\0" as *const u8 as *const ::core::ffi::c_char,
    b"guillemotright\0" as *const u8 as *const ::core::ffi::c_char,
    b"ellipsis\0" as *const u8 as *const ::core::ffi::c_char,
    b"perthousand\0" as *const u8 as *const ::core::ffi::c_char,
    b"questiondown\0" as *const u8 as *const ::core::ffi::c_char,
    b"grave\0" as *const u8 as *const ::core::ffi::c_char,
    b"acute\0" as *const u8 as *const ::core::ffi::c_char,
    b"circumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"tilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"macron\0" as *const u8 as *const ::core::ffi::c_char,
    b"breve\0" as *const u8 as *const ::core::ffi::c_char,
    b"dotaccent\0" as *const u8 as *const ::core::ffi::c_char,
    b"dieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"ring\0" as *const u8 as *const ::core::ffi::c_char,
    b"cedilla\0" as *const u8 as *const ::core::ffi::c_char,
    b"hungarumlaut\0" as *const u8 as *const ::core::ffi::c_char,
    b"ogonek\0" as *const u8 as *const ::core::ffi::c_char,
    b"caron\0" as *const u8 as *const ::core::ffi::c_char,
    b"emdash\0" as *const u8 as *const ::core::ffi::c_char,
    b"AE\0" as *const u8 as *const ::core::ffi::c_char,
    b"ordfeminine\0" as *const u8 as *const ::core::ffi::c_char,
    b"Lslash\0" as *const u8 as *const ::core::ffi::c_char,
    b"Oslash\0" as *const u8 as *const ::core::ffi::c_char,
    b"OE\0" as *const u8 as *const ::core::ffi::c_char,
    b"ordmasculine\0" as *const u8 as *const ::core::ffi::c_char,
    b"ae\0" as *const u8 as *const ::core::ffi::c_char,
    b"dotlessi\0" as *const u8 as *const ::core::ffi::c_char,
    b"lslash\0" as *const u8 as *const ::core::ffi::c_char,
    b"oslash\0" as *const u8 as *const ::core::ffi::c_char,
    b"oe\0" as *const u8 as *const ::core::ffi::c_char,
    b"germandbls\0" as *const u8 as *const ::core::ffi::c_char,
    b"onesuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"logicalnot\0" as *const u8 as *const ::core::ffi::c_char,
    b"mu\0" as *const u8 as *const ::core::ffi::c_char,
    b"trademark\0" as *const u8 as *const ::core::ffi::c_char,
    b"Eth\0" as *const u8 as *const ::core::ffi::c_char,
    b"onehalf\0" as *const u8 as *const ::core::ffi::c_char,
    b"plusminus\0" as *const u8 as *const ::core::ffi::c_char,
    b"Thorn\0" as *const u8 as *const ::core::ffi::c_char,
    b"onequarter\0" as *const u8 as *const ::core::ffi::c_char,
    b"divide\0" as *const u8 as *const ::core::ffi::c_char,
    b"brokenbar\0" as *const u8 as *const ::core::ffi::c_char,
    b"degree\0" as *const u8 as *const ::core::ffi::c_char,
    b"thorn\0" as *const u8 as *const ::core::ffi::c_char,
    b"threequarters\0" as *const u8 as *const ::core::ffi::c_char,
    b"twosuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"registered\0" as *const u8 as *const ::core::ffi::c_char,
    b"minus\0" as *const u8 as *const ::core::ffi::c_char,
    b"eth\0" as *const u8 as *const ::core::ffi::c_char,
    b"multiply\0" as *const u8 as *const ::core::ffi::c_char,
    b"threesuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"copyright\0" as *const u8 as *const ::core::ffi::c_char,
    b"Aacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"Acircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"Adieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"Agrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"Aring\0" as *const u8 as *const ::core::ffi::c_char,
    b"Atilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ccedilla\0" as *const u8 as *const ::core::ffi::c_char,
    b"Eacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ecircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"Edieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"Egrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"Iacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"Icircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"Idieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"Igrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ntilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"Oacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ocircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"Odieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ograve\0" as *const u8 as *const ::core::ffi::c_char,
    b"Otilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"Scaron\0" as *const u8 as *const ::core::ffi::c_char,
    b"Uacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ucircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"Udieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ugrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"Yacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ydieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"Zcaron\0" as *const u8 as *const ::core::ffi::c_char,
    b"aacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"acircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"adieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"agrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"aring\0" as *const u8 as *const ::core::ffi::c_char,
    b"atilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"ccedilla\0" as *const u8 as *const ::core::ffi::c_char,
    b"eacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"ecircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"edieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"egrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"iacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"icircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"idieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"igrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"ntilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"oacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"ocircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"odieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"ograve\0" as *const u8 as *const ::core::ffi::c_char,
    b"otilde\0" as *const u8 as *const ::core::ffi::c_char,
    b"scaron\0" as *const u8 as *const ::core::ffi::c_char,
    b"uacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"ucircumflex\0" as *const u8 as *const ::core::ffi::c_char,
    b"udieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"ugrave\0" as *const u8 as *const ::core::ffi::c_char,
    b"yacute\0" as *const u8 as *const ::core::ffi::c_char,
    b"ydieresis\0" as *const u8 as *const ::core::ffi::c_char,
    b"zcaron\0" as *const u8 as *const ::core::ffi::c_char,
    b"exclamsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Hungarumlautsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"dollaroldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"dollarsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"ampersandsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Acutesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"parenleftsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"parenrightsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"twodotenleader\0" as *const u8 as *const ::core::ffi::c_char,
    b"onedotenleader\0" as *const u8 as *const ::core::ffi::c_char,
    b"zerooldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"oneoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"twooldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"threeoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"fouroldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"fiveoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"sixoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"sevenoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"eightoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"nineoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"commasuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"threequartersemdash\0" as *const u8 as *const ::core::ffi::c_char,
    b"periodsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"questionsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"asuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"bsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"centsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"dsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"esuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"isuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"lsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"msuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"nsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"osuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"rsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"ssuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"tsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"ff\0" as *const u8 as *const ::core::ffi::c_char,
    b"ffi\0" as *const u8 as *const ::core::ffi::c_char,
    b"ffl\0" as *const u8 as *const ::core::ffi::c_char,
    b"parenleftinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"parenrightinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"Circumflexsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"hyphensuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"Gravesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Asmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Bsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Csmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Dsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Esmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Fsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Gsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Hsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ismall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Jsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ksmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Lsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Msmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Nsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Osmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Psmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Qsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Rsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ssmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Tsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Usmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Vsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Wsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Xsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ysmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Zsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"colonmonetary\0" as *const u8 as *const ::core::ffi::c_char,
    b"onefitted\0" as *const u8 as *const ::core::ffi::c_char,
    b"rupiah\0" as *const u8 as *const ::core::ffi::c_char,
    b"Tildesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"exclamdownsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"centoldstyle\0" as *const u8 as *const ::core::ffi::c_char,
    b"Lslashsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Scaronsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Zcaronsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Dieresissmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Brevesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Caronsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Dotaccentsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Macronsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"figuredash\0" as *const u8 as *const ::core::ffi::c_char,
    b"hypheninferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ogoneksmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ringsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Cedillasmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"questiondownsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"oneeighth\0" as *const u8 as *const ::core::ffi::c_char,
    b"threeeighths\0" as *const u8 as *const ::core::ffi::c_char,
    b"fiveeighths\0" as *const u8 as *const ::core::ffi::c_char,
    b"seveneighths\0" as *const u8 as *const ::core::ffi::c_char,
    b"onethird\0" as *const u8 as *const ::core::ffi::c_char,
    b"twothirds\0" as *const u8 as *const ::core::ffi::c_char,
    b"zerosuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"foursuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"fivesuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"sixsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"sevensuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"eightsuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"ninesuperior\0" as *const u8 as *const ::core::ffi::c_char,
    b"zeroinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"oneinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"twoinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"threeinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"fourinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"fiveinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"sixinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"seveninferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"eightinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"nineinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"centinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"dollarinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"periodinferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"commainferior\0" as *const u8 as *const ::core::ffi::c_char,
    b"Agravesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Aacutesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Acircumflexsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Atildesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Adieresissmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Aringsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"AEsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ccedillasmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Egravesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Eacutesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ecircumflexsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Edieresissmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Igravesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Iacutesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Icircumflexsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Idieresissmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ethsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ntildesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ogravesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Oacutesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ocircumflexsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Otildesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Odieresissmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"OEsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Oslashsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ugravesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Uacutesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ucircumflexsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Udieresissmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Yacutesmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Thornsmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"Ydieresissmall\0" as *const u8 as *const ::core::ffi::c_char,
    b"001.000\0" as *const u8 as *const ::core::ffi::c_char,
    b"001.001\0" as *const u8 as *const ::core::ffi::c_char,
    b"001.002\0" as *const u8 as *const ::core::ffi::c_char,
    b"001.003\0" as *const u8 as *const ::core::ffi::c_char,
    b"Black\0" as *const u8 as *const ::core::ffi::c_char,
    b"Bold\0" as *const u8 as *const ::core::ffi::c_char,
    b"Book\0" as *const u8 as *const ::core::ffi::c_char,
    b"Light\0" as *const u8 as *const ::core::ffi::c_char,
    b"Medium\0" as *const u8 as *const ::core::ffi::c_char,
    b"Regular\0" as *const u8 as *const ::core::ffi::c_char,
    b"Roman\0" as *const u8 as *const ::core::ffi::c_char,
    b"Semibold\0" as *const u8 as *const ::core::ffi::c_char,
];
#[no_mangle]
pub unsafe extern "C" fn sdsget_cff_sid(mut idx: uint16_t, mut str: cff_Index) -> sds {
    if idx as ::core::ffi::c_int <= 390 as ::core::ffi::c_int {
        return sdsnew(string_standard[idx as usize]);
    } else if str.count > 0 as arity_t
        && ((idx as ::core::ffi::c_int - 391 as ::core::ffi::c_int) as arity_t) < str.count
    {
        return sdsnewlen(
            str.data
                .offset(
                    *str.offset
                        .offset((idx as ::core::ffi::c_int - 391 as ::core::ffi::c_int) as isize)
                        as isize,
                )
                .offset(-(1 as ::core::ffi::c_int as isize))
                as *const ::core::ffi::c_void,
            (*str
                .offset
                .offset((idx as ::core::ffi::c_int - 390 as ::core::ffi::c_int) as isize))
            .wrapping_sub(
                *str.offset
                    .offset((idx as ::core::ffi::c_int - 391 as ::core::ffi::c_int) as isize),
            ) as size_t,
        );
    } else {
        return ::core::ptr::null_mut::<::core::ffi::c_char>();
    };
}
